application.name=ms-dacs2023-conector

dacs.exceptions.code-prefix=conector

spring.application.name=conector
spring.profiles.active=@activeProfile@

server.tomcat.basedir=.
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.prefix=ms_dacs2025_access_
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.file-date-format=yyyy-MM-dd
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)

keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:dacs}
keycloak.resource=${KEYCLOAK_RESOURCE:dacs-bff}
keycloak.credentials.secret=${KEYCLOAK_CREDENTIALS_SECRET:L9o1XhvkpPRVKh6ut7ncHGkAl0azC7tj}